### ISSUE TITLE
(Linux) File opener doesn't open after trying to load a rom, or save settings.

### ISSUE THREAD

**Issue by MintyFourScore** [SkyTemple/skytemple-randomizer#161]
Trying to select a rom opens the popup stating Wii U VC ROMs don't work, and no pop-up file handler appears for the user to load a ROM. Same thing with the save settings button, but theres no pop-up because its not meant to do that.

**Comment by theCapypara** [comment]
Are you using the Flatpak? Is there any error printed to the terminal if you run it via terminal?

**Comment by theCapypara** [comment]
Also which Desktop Environment und Distribution are you using?

**Comment by theCapypara** [comment]
Do other Flatpaks work for you? Do you have a Flatpak portal installed?
https://wiki.archlinux.org/title/XDG_Desktop_Portal

**Comment by MintyFourScore** [comment]
I don't use any other Flatpaks, and I do have a portal installed but still no avail.

**Comment by theCapypara** [comment]
Can you run it from the terminal with
```
flatpak run org.skytemple.Randomizer
```
and share the output when clicking the button to choose a ROM?

**Comment by MintyFourScore** [comment]
After running the app, the following output is shown:
`Gtk-Message: 17:55:47.124: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:55:47.125: Failed to load module "canberra-gtk-module"

(skytemple_randomizer:2): Gtk-WARNING **: 17:55:58.205: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop
`

**Comment by MintyFourScore** [comment]
After restarting the file opener does work, might be useful to have that as a dependency if possible.
