### ISSUE TITLE
Randomize TMs/HMs switch is incorrectly displayed as being off

### ISSUE THREAD

**Issue by Frostbyte0x70** [SkyTemple/skytemple-randomizer#207]
Originally reported at: https://discord.com/channels/710190644152369162/1243378875690520636

The "Randomize TMs/HMs" switch will initially be displayed as being disabled when a ROM is first loaded, but under the hood the setting is actually enabled (https://github.com/SkyTemple/skytemple-randomizer/blob/18706efe234127c947804bbed83c5fca9b0a8d22/skytemple_randomizer/data/default.json#L217).
This makes people believe TM randomization is disabled, but TMs do get randomized when the randomizer is run.
The switch works correctly when clicked, it's just a visual problem.

I couldn't immediately figure out why that switch in particular is not displayed correctly at first. I'm not very familiar with the new UI files.

**Comment by theCapypara** [comment]
Fixed in 2.1.0
