### ISSUE TITLE
Remember last folder

### ISSUE THREAD

**Issue by Frostbyte0x70** [SkyTemple/skytemple-randomizer#208]
Originally suggested here: https://discord.com/channels/710190644152369162/808273668752015380/1247016385247187016
The previous version of the randomzier would remember the last folder used when selecting an input ROM or when importing/exporting settings. On this version, that does not happen, so the user has to navigate back to their desired folder every time. This can be a bit annoying, especially if they are randomizing multiple ROMs. It would be nice if the randomizer remembered what the last folder selected by the user was and showed it directly when opening the file select dialog.

**Comment by theCapypara** [comment]
This may be possible with https://docs.gtk.org/gtk4/method.FileDialog.set_initial_folder.html - however probably only on Windows. 
On macOS and Linux Flatpak I don't think that this would work due to sandbox restrictions. If somebody wants to implement this, please test on all platforms.
