### ISSUE TITLE
Dll's not found

### ISSUE THREAD

**Issue by Kursed0** [SkyTemple/skytemple-randomizer#37]
When I try to randomize a rom I always get an error, I reinstalled it many times but the dlls are still missing. The Dll's that are missing are "MSVCP140.dll" and "VCRUNTIME140"

**Comment by Parakoopa** [comment]
You need to download the Visual Studio C++ Redistributable:
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by Kursed0** [comment]
I still get the error, that these dll's are missing.

**Comment by Parakoopa** [comment]
In this case try also installing the 32bit version:
https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by Kursed0** [comment]
Now it's fixed thank you!
