### ISSUE TITLE
Update for floor data IQ value

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/skytemple-randomizer#42]
See skytemple/skytemple-files#152.

Right now it only sets 0 and 1 (False and True to be exact). This should be switched to -1 to the max range of the base game.

**Comment by End45** [comment]
The base game normally only uses 0 and 1.

**Comment by theCapypara** [comment]
Are you sure? I figured it's shown that way in SkyTemple because it's casted to a bool before.
Why would it only boost by 1? Is that an oversight?

**Comment by End45** [comment]
I don't think so, it just works that way. 1 point per floor where the item is active. That's why the value was believed to be a boolean before.
