### ISSUE TITLE
Cannot exit the last room of Landslide Cave due to the boss room randomizer setting.

### ISSUE THREAD

**Issue by zapulater** [SkyTemple/skytemple-randomizer#69]
The last room of Landslide cave doesn't have a boss, but the room with deluxe boxes counts as a boss room (presumably) so it gets randomized. This, however, removed the warp that would normally take you out of the dungeon, resulting in an almost-softlock. I can wait until I starve and die or select the give up option, but then I'm subject to the usual penalties of leaving these ways. The best solution as of now is to just use escape orbs, which are very common on the dojo dungeons.
![image](https://user-images.githubusercontent.com/16521015/145471959-8a70810f-650c-4ace-bbe1-d5e2d6c7f9e7.png)

**Comment by ScottRWood** [comment]
Had a similar issue in the cave where you get the wonder egg (Manaphy)
