### ISSUE TITLE
Unable to enter into a dungeon besides the beachside one.

### ISSUE THREAD

**Issue by 77Arbiter** [SkyTemple/skytemple-randomizer#79]
As the title states. Unable to actually go into a dungeon from the crossroads after clearing the 'drowzee' fight. Clicking yes to head out keeps the team on the crossroads. I am, however, able to enter the specific beachside dungeon just fine, just unable to enter anything from the list from the crossroads including the test dungeon. Apologies if this issue is explained elsewhere, i couldn't find it in the discord the two times i joined and looked for it.

**Comment by theCapypara** [comment]
Hi! This happens if you and your partner exceed the body size limit.

**Comment by 77Arbiter** [comment]
Gotcha.  Guess that's what i get for choosing to make my Partner Wailord. If i change the body size limit in the editor, will it affect anything with my game? Also what would be the body size limit maximum?

**Comment by theCapypara** [comment]
Changing the body size in SkyTemple will probably not work, because the game as a failsafe checks the memory size of the sprites, which isn't editable.
If you were to force the game to load it would corrupt graphics because the game can't hold all the sprite data in memory.

**Comment by theCapypara** [comment]
Also not sure off the top of my head what the maximum is.

**Comment by 77Arbiter** [comment]
Darn alright. I'll just have to re-randomize and choose some other pokemon. Thank you!
