### ISSUE TITLE
Option to download missing portraits no longer works

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple-randomizer#83]
Originally reported at https://discord.com/channels/710190644152369162/808273668752015380/975566579611877406

Since the old sprites.pmdcollab.org site got moved to portraits.pmdcollab.org, the randomizer crashes when trying to connect to the old domain as it can't find the required files.

I was going to open a PR replacing the old URL but then I saw there's multiple copies and thought that it might be better to centralize the URL so it's not duplicated in several places... but I don't know what the best way of doing that would be.

These are all the references returned by GitHub's search:

- https://github.com/SkyTemple/skytemple-randomizer/blob/4e06fc4220cf79758d8b157edbe78d360f4e2e79/skytemple_randomizer/randomizer/portrait_downloader.py#L73
- https://github.com/SkyTemple/skytemple-randomizer/blob/9b9e702ffa380d3ae07b94631a7e68f4b6b51ac9/skytemple_randomizer/randomizer/seed_info.py#L420
- https://github.com/SkyTemple/skytemple-randomizer/blob/9b9e702ffa380d3ae07b94631a7e68f4b6b51ac9/skytemple_randomizer/randomizer/seed_info.py#L457
- https://github.com/SkyTemple/skytemple-randomizer/blob/4e06fc4220cf79758d8b157edbe78d360f4e2e79/skytemple_randomizer/config.py#L170

**Comment by End45** [comment]
@theCapypara

**Comment by theCapypara** [comment]
Oh right. Urgh. Probably time for a hotifx. I'll see if I can get one out this evening.
